apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sb-demo
  namespace: default
  labels:
    source: demo
    stack: frontend
    app: sb
spec:
  replicas: 1
  selector:
    matchLabels:
      source: demo
      app: sb
  template:
    metadata:
      labels:
        source: demo
        app: sb
    spec:
      containers:
      - name: primary
        image: docker.iflat.nhn.com/nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
      imagePullSecrets:
      - name: regcred

--- 
kind: Service
apiVersion: v1
metadata:
  name: sb-demo
  namespace: default
spec:
  selector:
    source: demo
    app: sb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
